// <auto-generated />
namespace ExemploMigrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adicao_campo_email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicao_campo_email));
        
        string IMigrationMetadata.Id
        {
            get { return "202009112025355_adicao_campo_email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
